/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 batman.glb --transform 
Files: batman.glb [3.16MB] > C:\Users\ADMIN\Downloads\anims\batman-transformed.glb [409.66KB] (87%)
Author: nitwit.friends (https://sketchfab.com/nitwit.friends)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hatch-batman-d5bf95c4f6ca4752aedc462307c46f5c
Title: Hatch Batman
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { editable as e } from "@theatre/r3f"

export function Batman(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/batman-transformed.glb')
  const { actions } = useAnimations(animations, group);

  
  useEffect(()=>{
    actions.stand.setEffectiveTimeScale(0.4)
    actions.stand.reset().fadeIn(0.5).play()
  },[])

  return (
    <e.group ref={group} theatreKey='batman' {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.M_MED_BlackMonday_Houston_Body} skeleton={nodes.Object_6.skeleton} scale={1.779} />
        <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.M_MED_BlackMonday_Houston_FaceAcc} skeleton={nodes.Object_8.skeleton} scale={1.779} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.M_Med_BlackMonday_Houston_Head} skeleton={nodes.Object_9.skeleton} scale={1.779} />
      </group>
    </e.group>
  )
}

useGLTF.preload('/batman-transformed.glb')
